#spring:
#  application:
#    name: API_GATEWAY
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://keycloak:8080/realms/notification_system
#server:
#  port: 9090
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: API_GATEWAY
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/notification_system
server:
  port: 9090

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka