#spring:
#  application:
#    name: USER_MANAGEMENT
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: keycloak:8080/realms/notification_system
#
#server:
#  port: 9091
#
#keycloak:
#  server-url: keycloak:8080
#  realm: notification_system
#  client-id: notification_system_backend
#  client-secret: sZGBPhvINGSNnQDpnmSf1apc9Zh8zzRu
#  grant-type: client_credentials
#
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: USER_MANAGEMENT
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/notification_system

server:
  port: 9091

keycloak:
  server-url: http://localhost:8181
  realm: notification_system
  client-id: notification_system_backend
  client-secret: sZGBPhvINGSNnQDpnmSf1apc9Zh8zzRu
  grant-type: client_credentials

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

